### ISSUE TITLE
Cannot initialize WarningLists (Python2.x)

### ISSUE THREAD

**Issue by TheFausap** [MISP/PyMISPWarningLists#11]
Hello,

I'm trying the example code (and also the test code in the repo), but I got a problem with the module initialization:

```
Traceback (most recent call last):
  File "./example_domaincheck.py", line 10, in <module>
    from pymispwarninglists import WarningLists
  File "/root/PyMISPWarningLists/pymispwarninglists/__init__.py", line 4, in <module>
    from .api import WarningLists, EncodeWarningList
  File "/root/PyMISPWarningLists/pymispwarninglists/api.py", line 44
    raise PyMISPWarningListsError(f'Unexpected type ({self.warninglist["type"]}), please update the expected_type list')
```
I understand the module works with Python 3.x, but is there any chance to got it working with Python2?

thanks,
Fausto

**Comment by Rafiot** [comment]
No, sorry. Python 2.7 is EOL since January 2020, we won backport the module.

**Comment by TheFausap** [comment]
Hello Rafiot,
I'm not saying to backport the module, I understand your point of view, I am just asking to understand if there's a way to make it working while I am updating my Splunk installation to work with Python3.
thanks,
Fausto

**Comment by cvandeplas** [comment]
python 2 and 3 can happily live together on one system. So you should be able to install python3 without affecting the rest of your system.

**Comment by TheFausap** [comment]
Yes, but my problem is running this module in a custom streaming command in a Splunk session. Splunk until 7.x ships only with Python2.7 so I have to update to Splunk 8.x, but this is not so fast. That's the reason of this weird request. :)

**Comment by iglocska** [comment]
That sounds like an issue to raise with Splunk :)

**Comment by cvandeplas** [comment]
This is the beauty of open source software: if your closed-source vendor refuses to provide support that pleases you, you can still resort to the open source code to fix it yourself.

**Comment by cvandeplas** [comment]
thinking about it, you could also make a python2 script that calls a python3 script in a subprocess :-)

**Comment by TheFausap** [comment]
> thinking about it, you could also make a python2 script that calls a python3 script in a subprocess :-)

Yes, this is the approach I am pursuing right now. But I have some issues with subprocess.Popen call.

**Comment by TheFausap** [comment]
> That sounds like an issue to raise with Splunk :)

The real issue here, the long time I have to wait to update to Splunk 8.x :)

**Comment by TheFausap** [comment]
> > thinking about it, you could also make a python2 script that calls a python3 script in a subprocess :-)
> 
> Yes, this is the approach I am pursuing right now. But I have some issues with subprocess.Popen call.

Ok, it works :D Thanks again for the hint.
