### ISSUE TITLE
Update Pypi package

### ISSUE THREAD

**Issue by sisoma2** [MISP/PyMISPWarningLists#12]
The last update in Pypi of the package it's from Apr 7, 2020 and it misses some bug fixes like the slow_search fix.
[pymispwarninglists Pypi package](https://pypi.org/project/pymispwarninglists/#description)

**Comment by Rafiot** [comment]
Good point, on it.

**Comment by Rafiot** [comment]
Done!

**Comment by sisoma2** [comment]
Thanks! :D
