### ISSUE TITLE
Ngrok domains failed to be detected

### ISSUE THREAD

**Issue by sisoma2** [MISP/PyMISPWarningLists#13]
Hi,

I'm testing the domain '0.tcp.eu.ngrok.io' with the script warninglist_test.py and fails to be detected.
The domain 'ngrok.io' is at the second-level-tlds JSON list file.

![imagen](https://user-images.githubusercontent.com/7660940/114169765-49c51780-9932-11eb-859e-8b9f412a982c.png)
![imagen](https://user-images.githubusercontent.com/7660940/114169802-55184300-9932-11eb-967d-ad7832e9a5c3.png)

**Comment by fukusuket** [comment]
If you instantiate the warning list as below(slow_search=True), it will match the Ngrok domain.
```
warninglists = WarningLists(slow_search=True)
...
for domain in domain_list:
    r = warninglists.search(domain)
```

Please see also #16.
