### ISSUE TITLE
License

### ISSUE THREAD

**Issue by lroellin** [MISP/PyMISPWarningLists#2]
Dear Creator

We would like to use your code for a commercial product, but we couldn't identify any license information. Can you please tell us the terms of use (e.g. commercial use, distribution, modification etc.) or under which license we can use your code?

(This does not concern the actual lists, they're correctly licensed under CC0 (meaning Public Domain but in a more legal way ;) ))

Thank you very much and kind regards

On behalf of Swisscom (Schweiz) AG

Lukas Röllin

**Comment by adulau** [comment]
Sure very good point.

The programming libraries of MISP projects are usually 3-clause BSD-like license.

We just clarified this in the repository of this project. https://github.com/MISP/PyMISPWarningLists/commit/dc95e1b4e78ebd67737269f81d14ab31bb7ac2e2 

Thank you very much for the feedback and feel free to reopen the issue if this is not solved.
