### ISSUE TITLE
Slow search for hostnames doesn't work as expected

### ISSUE THREAD

**Issue by ilyaglow** [MISP/PyMISPWarningLists#6]
If the #5 will be accepted, we have another problem with a slow search. This test case won't pass:
```diff
diff --git a/tests/tests.py b/tests/tests.py
index a8e727c..4ce7062 100644
--- a/tests/tests.py
+++ b/tests/tests.py
@@ -46,3 +46,5 @@ class TestPyMISPWarningLists(unittest.TestCase):
         self.assertEqual(results[0].name, 'List of known google domains')
         results = self.warninglists.search('something.files.1drv.com')
         self.assertEqual(results[0].name, 'List of known microsoft domains')
+        results = self.warninglists.search('arbitrary-domain-1e100.net')
+        self.assertNotEqual(results[0].name, 'List of known google domains')
```

**Comment by ilyaglow** [comment]
Basically the `arbitrary-domain-1e100.net` should not be indicated as a known google domain, just because it contains `1e100.net` in it.

**Comment by Rafiot** [comment]
right, I'll patch that to :)

`arbitrary-domain.1e100.net` <- should work

**Comment by kimmoal** [comment]
May I ask ask, in what situation the algorithm to match hostnames is considered valid?
```python
        elif self.type == 'hostname':
            # Expected to match on hostnames in URLs (i.e. the search query is a URL)
            # So we do a reverse search if any of the entries in the list are present in the URL
            # i.e.: value = 'http://foo.blah.de/meh' self.list == ['blah.de', 'blah.fr']
            return any(v in value for v in self.list)`
```
Getting too many false positives hits for domain `g.co` from Google owned domains list.
For example `phishking.co.uk` is matched. We should be parsing the `value` as URL/hostname and checking it in the hostname context.

**Comment by Rafiot** [comment]
That should solve your problem, can you give it a try?

**Comment by ilyaglow** [comment]
The afa7eb4 commit doesn't cover my original issue :)

@Rafiot please take a look at #9
